observatorioapp/Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using observatorioapp.Models;
using observatorioapp.Data;

namespace observatorioapp.Controllers
{
    public class ContactoController : Controller
    {
        
        private readonly ApplicationDbContext _context;

        public ContactoController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(){
            return View();
        }

        [HttpPost]
        public IActionResult RegistrarContacto(Contacto c){
            
            c.Fecha = DateTime.Now;

            if(ModelState.IsValid){
                _context.Add(c);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }else{
                return View("Index");
            }
        }
        
    }
}

observatorioapp/Controllers/FiltroController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using observatorioapp.Data;

namespace observatorioapp.Controllers
{
    public class FiltroController : Controller 
    {

      private readonly ApplicationDbContext _context; 

      public FiltroController(ApplicationDbContext context)
      {
          _context = context;
      } 
      
    public IActionResult Busqueda(){
        
        var entidades = _context.DataEntidades.ToList();
        ViewBag.items = entidades;
        return View();
    }

      public IActionResult Resultados(string titulo, int idEntidad, string fechainicio, string fechafin){
        
        var normativas = _context.DataNormativas.Include(n => n.entidad).ToList();
        
        var query1 = normativas;
        var query2 = normativas;
        var query3 = normativas;

        if(titulo != null){
          query1 =  query1.Where(n => n.titulo.Contains(titulo)).ToList();
        }
        
        if(idEntidad != 0){
          query2 = query2.Where(n => n.entidad.Id == idEntidad).ToList();
        }

        if(fechainicio != null || fechafin != null){
          
          if(fechainicio == null){
            query3 = query3.Where(n => n.fecha >= DateTime.ParseExact("0001-01-01", "yyyy-MM-dd", null) && n.fecha <= DateTime.ParseExact(fechafin, "yyyy-MM-dd", null)).ToList();
          }else if(fechafin == null){
            query3 = query3.Where(n => n.fecha >= DateTime.ParseExact(fechainicio, "yyyy-MM-dd", null) && n.fecha <= DateTime.Now).ToList();
          }else{
            query3 = query3.Where(n => n.fecha >= DateTime.ParseExact(fechainicio, "yyyy-MM-dd", null) && n.fecha <= DateTime.ParseExact(fechafin, "yyyy-MM-dd", null)).ToList();
          }

        }

        var resultado = query1.Intersect(query2).Intersect(query3).ToList();
        return View(resultado);

      }

       public IActionResult DownLoadNormativa(int id){
        
           var normativas = _context.DataNormativas.Find(id);
           return File(normativas.archivo, "application/pdf", normativas.nombrefile);  
          

       }

    }
}

observatorioapp/Controllers/NormativaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using observatorioapp.Data;
using observatorioapp.Models;

namespace observatorioapp.Controllers
{
    public class NormativaController : Controller
    {
        
        private readonly ApplicationDbContext _context;
        private readonly ILogger<NormativaController> _logger;

        public NormativaController(ILogger<NormativaController> logger  , ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        
        [Authorize(Roles = "Admin")]
        public IActionResult AccionNormativa(){

            return View();
        }
        
        [Authorize(Roles = "Admin")]
        public IActionResult RegistrarNormativa(){

            var entidades = _context.DataEntidades.ToList();
            ViewBag.items = entidades;
            return View();
        }
        
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult RegistrarNormativa(Normativa normativa , int idEntidad , List<IFormFile> files){
            var flag = false;

            if(ModelState.IsValid){

                if(files.Count > 0 ){

                    foreach(var file in files){

                       Console.WriteLine(Path.GetExtension(file.FileName).Substring(1));

                        if(Path.GetExtension(file.FileName).Substring(1) == "pdf"){
                      
                          Stream str = file.OpenReadStream();
                          BinaryReader br = new BinaryReader(str);
                          Byte [] fileDet = br.ReadBytes((Int32) str.Length);
                          normativa.archivo = fileDet;
                          normativa.nombrefile = Path.GetFileName(file.FileName);

                        }else {
                            
                            flag = true;
                            break;
                
                        }

 
                    }


                
                }

                if(flag == true){

                     var entidades = _context.DataEntidades.ToList();
                     ViewBag.items = entidades;
                     ModelState.AddModelError("files" , "Solo se aceptan documentos con la extension PDF");
                     return View(normativa);
                }

                var entity = _context.DataEntidades.Find(idEntidad);
                normativa.entidad = entity;
                _context.Add(normativa);
                _context.SaveChanges();
                
                return RedirectToAction("ListarNormativa");

            }

            var entidade = _context.DataEntidades.ToList();
            ViewBag.items = entidade;
            return View(normativa);

        }
      
        
         [Authorize(Roles = "Admin")]
         public IActionResult ListarNormativa(){

             var normativas = _context.DataNormativas.Include(e => e.entidad).ToList();

             return View(normativas);
         }
         
         [Authorize(Roles = "Admin")]
         public IActionResult EditarNormativa(int id){

               var normativa = _context.DataNormativas.Include(e => e.entidad).FirstOrDefault(s => s.id == id);

               if(normativa == null){

                   return NotFound();
               }
              
               var entica = _context.DataEntidades.Find(normativa.entidad.Id);
               var entidades = _context.DataEntidades.Where(s => s.Id != normativa.entidad.Id).ToList();
               
               ViewBag.items = entidades;
               ViewBag.item = entica;
               return View(normativa);

         }
         
         [Authorize(Roles = "Admin")]
         [HttpPost]
         public IActionResult EditarNormativa([Bind("id , numero , titulo , descripcion , fecha , nombrefile , archivo")] Normativa normativa ,  int idEntidad , List<IFormFile> files){
            var flag = false;
            var entica = _context.DataEntidades.Find(idEntidad);
            var entidades = _context.DataEntidades.Where(e => e.Id != idEntidad).ToList();
            

             if(ModelState.IsValid){

               if(files.Count > 0){

                    foreach(var file in files){

                       Console.WriteLine(Path.GetExtension(file.FileName).Substring(1));

                        if(Path.GetExtension(file.FileName).Substring(1) == "pdf"){
                      
                          Stream str = file.OpenReadStream();
                          BinaryReader br = new BinaryReader(str);
                          Byte [] fileDet = br.ReadBytes((Int32) str.Length);
                          normativa.archivo = fileDet;
                          normativa.nombrefile = Path.GetFileName(file.FileName);

                        }else {
                            
                            flag = true;
                            break;
                
                        }

 
                    }

                  

               }else {

                  var norma = _context.DataNormativas.AsNoTracking().Where(s => s.id == normativa.id).FirstOrDefault();
                  normativa.archivo = norma.archivo;
                  normativa.nombrefile = norma.nombrefile;


               }

                 if(flag == true){
                    
                    
                     ViewBag.items = entidades;
                     ViewBag.item = entica;
                     ModelState.AddModelError("files" , "Solo se aceptan documentos con la extension PDF");
                     return View(normativa);
                }

                
                 var entity = _context.DataEntidades.Find(idEntidad);
                 normativa.entidad = entity;
                 _context.Update(normativa);
                 _context.SaveChanges();
                 return RedirectToAction("ListarNormativa");

             }


            
             ViewBag.items = entidades;
             ViewBag.item = entica;
            
             return View(normativa);
         }

       
       [Authorize(Roles = "Admin")]
       public IActionResult EliminarNormativa(int id){
            
             var normativa = _context.DataNormativas.Find(id);

             if(normativa == null){

                 return NotFound();
             }

             _context.DataNormativas.Remove(normativa);
             _context.SaveChanges();

            return RedirectToAction("ListarNormativa");
       }

       public IActionResult DownLoadNormativa(int id){
        
           var normativas = _context.DataNormativas.Find(id);
           return File(normativas.archivo, "application/pdf", normativas.nombrefile);  
          

       }


    }
}

observatorioapp/Controllers/NoticiaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using observatorioapp.Models;
using observatorioapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace observatorioapp.Controllers
{
    public class NoticiaController : Controller
    {
        
        private readonly ApplicationDbContext _context;

        public NoticiaController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {    

            var noticias = _context.DataNoticias.ToList();
            return View(noticias);

        }

         [Authorize(Roles = "Admin")]
        public IActionResult RegistrarNoticia(){
            return View();
        }

         [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult RegistrarNoticia(Noticia noticia, int datos){
            if(ModelState.IsValid){
            _context.Add(noticia);
            _context.SaveChanges();
            return RedirectToAction("ListarNoticia");
            }   
            return View();          
        }

          [Authorize(Roles = "Admin")]
        public IActionResult EleccionNoticia(){
            return View();
        }

         [Authorize(Roles = "Admin")]

        public IActionResult ListarNoticia(){
            var noticia = _context.DataNoticias.ToList();
            return View(noticia);
        }

         [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id){
            var noticia = _context.DataNoticias.Find(id);
            _context.DataNoticias.Remove(noticia);
            _context.SaveChanges();
            return RedirectToAction("ListarNoticia");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id){
            Noticia objNoticia = _context.DataNoticias.Find(id);
            if(objNoticia == null){
                return NotFound();
            }
            return View(objNoticia);
        }

         [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(int id, [Bind("Id, Titulo, LinkImagen, LinkNoticia")] Noticia objNoticia){
                _context.Update(objNoticia);
                _context.SaveChanges();
                ViewData["Message"] = "NOTICIA ACTUALIZADA";
                return RedirectToAction("ListarNoticia");
        }

    }
}

observatorioapp/Controllers/UniversidadController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using observatorioapp.Models;
using observatorioapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace observatorioapp.Controllers
{
    public class UniversidadController : Controller
    {
        
        private readonly ApplicationDbContext _context;

        public UniversidadController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {   
            var universidades = _context.DataUniversidades.ToList();

            return View(universidades);
        }

         [Authorize(Roles = "Admin")]

        public IActionResult EleccionUniversidad(){
            return View();
        }

         [Authorize(Roles = "Admin")]
        public IActionResult RegistrarUniversidad(){
            return View();
        }
        
         [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult RegistrarUniversidad(Universidad universidad, int datos){
            if(ModelState.IsValid){
            _context.Add(universidad);
            _context.SaveChanges();
            return RedirectToAction("ListarUniversidad");
            }   
            return View();          
        }


         [Authorize(Roles = "Admin")]

        public IActionResult ListarUniversidad(){
            var universidad = _context.DataUniversidades.ToList();
            return View(universidad);
        }

         [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id){
            var universidad = _context.DataUniversidades.Find(id);
            _context.DataUniversidades.Remove(universidad);
            _context.SaveChanges();
            return RedirectToAction("ListarUniversidad");
        }

         [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id){
            Universidad objUniversidad = _context.DataUniversidades.Find(id);
            if(objUniversidad  == null){
                return NotFound();
            }
            return View(objUniversidad );
        }

         [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(int id, [Bind("id, nombre, telefono, direccion, aniversario, nombrerector, apellidorector, fechanacimientorector, correorector, imagen")] Universidad  objUniversidad ){
            _context.Update(objUniversidad );
            _context.SaveChanges();
            ViewData["Message"] = "UNIVERSIDAD ACTUALIZADA";
            return RedirectToAction("ListarUniversidad");
        }
    }
}

observatorioapp/Views/Shared/_Administrador.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <link rel="stylesheet" href="~/css/admin.css">
    
</head>

<body>

    <input type="checkbox" id="nav-toggle">
    <div class="sidebar">
        <div class="sidebar-brand">
           <a asp-controller="Home" asp-action="Index"> <h1 style="color: black;"> <img src="https://img.icons8.com/material/26/000000/home--v5.png"/> <span>OUP</span></h1> </a>
        </div>
        <hr>
        <!--Secciones-del-tablero-->
        <div class="sidebar-menu">
            <ul>
                <li>
                    <a href="" class="active"><span class="las la-home"></span>
                    <span>Tablero</span></a>
                </li>
               
                <li>
                    <a class="nav-link" asp-controller="Universidad" asp-action="EleccionUniversidad"><span class="las la-book-medical"></span>
                    <span>UNIVERSIDADES</span></a>
                </li>
                <li>
                    <a class="nav-link" asp-controller="Noticia" asp-action="EleccionNoticia"><span class="las la-book-medical"></span>
                    <span>NOTICIAS</span></a>
                </li>
            
              </li>
                <li>
                    <a class="nav-link" asp-controller="Normativa" asp-action="AccionNormativa"><span class="las la-book-medical"></span>
                    <span>NORMATIVAS</span></a>
                </li>

            </ul>
        </div>
    </div>

    <div class="main-content">
        <header>
            <h2>
                <label for="nav-toggle">
                    <span class="las la-bars"></span>
                </label> Tablero
            </h2>

            <div class="search-wrapper">
                <span class="las la-search"></span>
                <input type="search" placeholder="Buscar aquí" />
            </div>
            <div class="user-wrapper">
                <img src="assets/img/jhoel.jpeg" width="40px" height="40px" alt="">
                <div>
                    <h4>Administrador</h4>
                    <small>Super Admin</small>
                </div>
            </div>
        </header>

   

     @RenderBody()

     </div>


     @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

observatorioapp/Views/Shared/_Filtros.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<title>@ViewData["Title"] - ASUP</title>
    <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="~/css/filtro.css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link href="~/css/styles.css" rel="stylesheet" />

	
</head>
<body onload="redireccion();">

	<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
		<div class="container">
		 <a class="navbar-brand"><img src="~/img/oup.png" /></a>

		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Menu
			<i class="fas fa-bars ms-1"></i>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
					<li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Universidad" asp-action="Index">Universidad</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Nosotros">Nosotros</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Noticia" asp-action="Index">Noticias</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Contacto" asp-action="Index">Contactanos</a></li>
				  <partial name="_LoginPartial" />
			</ul>
		</div>
	</div>
</nav>

<br>
<br>
<br>
	

       @RenderBody()
       


	     <!-- Footer-->
        <footer class="footer py-4 bg-secondary mt-5">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; Your Website 2021</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="https://twitter.com/asupoficial/status/1238812331771125761?lang=es"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/ASUPoficiial/"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://pe.linkedin.com/company/asupasociaciondeuniversidadesdelperu"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                        <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>



   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

 <script src="js/jquery-3.2.1.js"></script>

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="~/js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
	
       <script src="~/js/site.js"></script>

     @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

observatorioapp/Views/Shared/_Iniciar.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Iniciar Sesión</title>
    <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
    <link rel="stylesheet" href="~/css/login.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">

</head>

<body>


     
    
            @RenderBody()
       
    

    @await RenderSectionAsync("Scripts", required: false)
   
</body>

<script src="~/js/site.js"></script>

</html>

observatorioapp/Views/Shared/_Plantilla.cshtml
@model observatorioapp.Models.Contacto

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>OUP</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="~/css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">

                <a class="navbar-brand"><img src="~/img/oup.png" /></a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Universidad" asp-action="Index">Universidad</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Nosotros">Nosotros</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Noticia" asp-action="Index">Noticias</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Contacto" asp-action="Index">Contactanos</a></li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Masthead-->
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading"></div>
                <div class="masthead-heading text-uppercase"></div>
                <br><br><br><br><br>
                <a class="btn btn-primary btn-xl text-uppercase" href="https://unmsm.edu.pe/noticias-y-eventos/noticias/noticia-detalle/san-marcos-se-posiciona-como-la-mejor-universidad-del-peru-segun-ranking-internacional">Ver más</a>
            </div>
        </header>
        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
                <div class="row text-center">
                    <div class="col-md-4">
                        <span  class="fa-stack fa-4x">
                            
                            
                            <i  class="fas fa-circle fa-stack-2x text-white"></i>
                            <i class="fas fa-chart-pie fa-stack-1x text-dark"></i>
                        </span>
                        <a asp-controller="DatosEstadisticos" asp-action="Index" style="text-decoration: none; "><h4 class="my-3">Datos Estadísticos</h4></a>
                        <p class="text-muted">¿Buscas datos y evidencias sobre la violencia?</p>
                    </div>
                    <div class="col-md-4">
                        <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-white"></i>
                            
                            <i class="fas fa-search fa-stack-1x text-dark"></i>
                        </span>
                        <a asp-controller="Filtro" asp-action="Busqueda" style="text-decoration: none; "><h4 class="my-3">Búsqueda de Información</h4></a>
                        <p class="text-muted">Conoce acerca de las normativas, leyes, proyectos de ley</p>
                    </div>
                    <div class="col-md-4">
                        <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-white"></i>
                            <i class="fas fa-archive fa-stack-1x text-dark"></i>
                        </span>
                        <a href="#" style="text-decoration: none; "><h4 class="my-3">Repositorio</h4></a>
                        <p class="text-muted">¿Necesitas conocer mejor el tema?</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Portfolio Grid-->
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <!-- About-->
        
        <!-- Team-->
        
        <!-- Clients-->
      
        <!-- Contact-->
        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; OUP</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="https://twitter.com/asupoficial/status/1238812331771125761?lang=es"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/ASUPoficiial/"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://pe.linkedin.com/company/asupasociaciondeuniversidadesdelperu"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                   
                </div>
            </div>
        </footer>
        <!-- Portfolio Modals-->
        <!-- Portfolio item 1 modal popup-->
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="~/js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>